# ----------------------------------------------------------------------
# | General Settings                                                   |
# ----------------------------------------------------------------------

# Make window index start at 1
set -g base-index 1

# Make pane index start at 1
setw -g pane-base-index 1

# Remove delay when sending commands
# (default is 500 milliseconds)
set -g escape-time 1

# set shell properly
set -g default-shell $SHELL

set -g default-terminal "tmux-256color"

# ----------------------------------------------------------------------
# | Key Mappings                                                       |
# ----------------------------------------------------------------------

# Change the key combination for the PREFIX key to `ctrl-s`
set -g prefix C-s
unbind-key C-b

# Make tmux send the PREFIX to an application running
# within tmux simply by pressing PREFIX key twice
bind C-s send-prefix

# intuitive split-window
bind - split-window -v
bind | split-window -h

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Remap the copy & paste keys to work as in vim
unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer
bind-key -T copy-mode-vi "v" send-keys -X begin-selection
bind-key -T copy-mode-vi "y" send-keys -X copy-selection

# [ PREFIX + H/J/K/L ] Resize pane
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# [ PREFIX + r ] Reload tmux config
bind r source-file ~/.tmux.conf \; display "tmux configs reloaded"

# ----------------------------------------------------------------------
# | Vim Navigation                                                     |
# ----------------------------------------------------------------------

is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R

# ----------------------------------------------------------------------
# | Status bar                                                         |
# ----------------------------------------------------------------------

# Periodically refresh the status bar
set -g status-interval 60

# Customize what is displayed
set -g status-justify left
set -g status-left-length 50
set -g status-right-length 150

set -g status-left ""
set -g status-right "\
#[fg=colour6]🙌 #(whoami) \
#[fg=colour10]📆 %h %d #(date "+%%H:%%M") \
#[fg=colour4]🔊 #(dig +short myip.opendns.com @resolver1.opendns.com) \
"

# Display things in 256 colors
set -g default-terminal "screen-256color"

# Default colors
set -g status-style "bg=default, fg=default"

# Colors for window list
setw -g window-status-style "fg=default bg=default"

# Colors for active window
setw -g window-status-current-format "✨#[fg=white] #W"

setw -g window-status-format '#[fg=black] #W'

# Command Line
set -g message-style "fg=black bg=default"

# Pane divider
set -g pane-active-border-style "bg=default fg=default"

set -g pane-border-style "bg=default fg=default"

set -ga terminal-overrides ',*256color*:smcup@:rmcup@'
