format = """
[╭──](bold white) $directory$git_branch$git_status$git_commit$status$cmd_duration
[╰──> ](bold white)
"""

# disable the blank line at the start of the prompt
add_newline = false

[git_commit]
commit_hash_length = 4
disabled = false
only_detached = false

[status]
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
disabled = false

[cmd_duration]
min_time = 10000
format = 'tooks [$duration](bold yellow)'
