#!/usr/bin/env bash

function usage {
    echo "Usage: $0 <remote_host> <remote_dir> <local_dir>"
    exit 1
}

function pull_directory {
    local remote_host=$1
    local remote_dir=$2
    local local_dir=$3

    if [ ! -d "$local_dir" ]; then
        mkdir -p "$local_dir"
    fi

    local remote_dirname
    remote_dirname=$(ssh "$remote_host" "basename \"$remote_dir\"")
    local tar_file="${remote_dirname}.tar.gz"

    if ! ssh "$remote_host" "cd \$(dirname \"$remote_dir\") && tar czf \"$tar_file\" \$(basename \"$remote_dir\")"; then
        echo "Error: Failed to create tar archive of remote directory"
        exit 1
    fi

    remote_tar_path=$(dirname "$remote_dir")/"$tar_file"
    if ! scp "$remote_host:$remote_tar_path" "$local_dir"; then
        echo "Error: Failed to download tar file from remote server"
        ssh "$remote_host" "rm \"$remote_tar_path\""
        exit 1
    fi

    ssh "$remote_host" "rm \"$remote_tar_path\""

    if ! (cd "$local_dir" && tar xzf "$tar_file"); then
        echo "Error: Failed to extract tar archive locally"
        rm "$local_dir/$tar_file"
        exit 1
    fi

    # Remove the local zip file
    rm "$local_dir/$tar_file"
    echo "Download complete!"
}

# Check the number of arguments
if [ $# -ne 3 ]; then
    usage
fi

pull_directory "$1" "$2" "$3"
