#!/bin/bash

# use python interpreter for user
if [ -d "$HOME/.venv" ]; then
    source "$HOME/.venv/bin/activate"
else
    echo "No python environment found"
fi

# prompt by starship
eval "$(starship init bash)"

# alias
alias ll='ls -alh'
alias path='echo -e ${PATH//:/\\n}'
alias vim='NVIM_LIGHTWEIGHT=1 nvim'
alias vim-full='NVIM_LIGHTWEIGHT=0 nvim'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias grep='grep --color=auto'
alias ssh-detach='ssh -fNT'
alias dra='docker ps -aq | xargs -r docker rm -f'
alias dpa='docker images -aq | xargs -r docker rmi -f'
alias dex='docker exec -it'

# environment variables
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export EDITOR=nvim
export TERM="xterm-256color"
export PATH="$HOME/.local/bin:$PATH"
export COLORTERM=truecolor
SHELL="$(which bash)" && export SHELL
export HISTTIMEFORMAT="%F %T " # Add timestamp to history

function extract() {
    if [ -f "$1" ]; then
        case "$1" in
        *.tar.bz2) tar xjf "$1" ;;
        *.tar.gz) tar xzf "$1" ;;
        *.tar.xz) tar xJf "$1" ;;
        *.bz2) bunzip2 "$1" ;;
        *.rar) unrar x "$1" ;;
        *.gz) gunzip "$1" ;;
        *.tar) tar xf "$1" ;;
        *.tbz2) tar xjf "$1" ;;
        *.tgz) tar xzf "$1" ;;
        *.zip) unzip "$1" ;;
        *.Z) uncompress "$1" ;;
        *.7z) 7z x "$1" ;;
        *) echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}
